### PR TITLE
✨ upgrade code to handle surrealdb v2

### PR DESCRIPTION
**Pull request by Odonno**
Thank you for submitting this pull request! We appreciate you spending the time to work on these changes.

## What does this change do?

Handle surrealdb v2

## What is your testing strategy?

Integration tests

## Is this related to any issues?

N/A

## Have you read the [Contributing Guidelines](https://github.com/surrealdb/surrealdb.net/blob/main/CONTRIBUTING.md)?

- [x] I have read the [Contributing Guidelines](https://github.com/surrealdb/surrealdb.net/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by J05HM0N5TER** [comment]
Hi. I am truly interested in this feature because v2 of surreal has some features that I could benefit from with my project. Is there any way I can help push this forwards? 
I am not familiar with this code base, but I can at least help test this, and do some simple debugging if that would help.

**Comment by mohammad-hosein-shahpouri** [comment]
Is there a plan to fix the last failing test?

**Comment by armanradan** [comment]
I hope this pr gets merged soon. We really need it for V2

**Comment by armanradan** [comment]
@Odonno Would you please fix the issue with workflow so we can finally use v2 ?

**Comment by mohammad-hosein-shahpouri** [comment]
c'mon merge it @tobiemh 
mmbqqoqrtgw81

**Comment by mohammad-hosein-shahpouri** [comment]
c'mon merge it

**Pull request merged**
